
const legalContent = {
    terms: {
        title: "Terms & Conditions",
        content: `
            <div class="space-y-4">
                <p class="text-xs text-slate-400 italic">Last Updated: March 2026</p>
                <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://www.parkconscious.in" class="text-teal-500 hover:underline">https://www.parkconscious.in</a> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>
                <p>The Platform is owned by <strong>Park Conscious</strong>, a company incorporated under the Companies Act, 1956 with its registered office at A 111 yadav gali karawal nagar road delhi 110094 (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').</p>
                <p>Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.</p>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Use of Platform</h4>
                <ol class="list-decimal pl-5 space-y-2">
                    <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration.</li>
                    <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered.</li>
                    <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable.</li>
                    <li>The contents of the Platform and the Services are proprietary to us. You will not have any authority to claim any intellectual property rights.</li>
                    <li>Unauthorized use of the Platform and/or the Services may lead to action against you.</li>
                    <li>You agree to pay us the charges associated with availing the Services.</li>
                    <li>You agree not to use the Platform for any purpose that is unlawful, illegal or forbidden.</li>
                    <li>The Services may contain links to other third party websites. On accessing these links, you will be governed by their terms.</li>
                    <li>You understand that upon initiating a transaction you are entering into a legally binding contract with the Platform Owner.</li>
                    <li>You shall indemnify and hold harmless Platform Owner, its affiliates, and employees from any claim or demand arising out of your breach of these Terms.</li>
                    <li>Parties shall not be liable for any failure to perform due to force majeure events.</li>
                    <li>These Terms shall be governed by and construed in accordance with the laws of India.</li>
                    <li>All disputes shall be subject to exclusive jurisdiction of the courts in Delhi.</li>
                </ol>
            </div>
        `
    },
    privacy: {
        title: "Privacy Policy",
        content: `
            <div class="space-y-4">
                <p>This Privacy Policy describes how Park Conscious and its affiliates collect, use, share, protect or otherwise process your information through our website <a href="https://www.parkconscious.in" class="text-teal-500 hover:underline">https://www.parkconscious.in</a>.</p>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Collection of Information</h4>
                <p>We collect your personal data when you use our Platform, services or otherwise interact with us. This includes name, date of birth, address, telephone number, email ID, and proof of identity. Sensitive personal data, such as bank account or payment instrument information, may be collected with your consent to enable specific features.</p>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Usage of Data</h4>
                <p>We use personal data to provide the services you request, market to you (with opt-out ability), assist sellers in fulfilling orders, resolve disputes, and customize your experience.</p>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Sharing of Data</h4>
                <p>We may share your data within our group entities and with third-party service providers (logistics, payment issuers) to fulfill your requests and comply with legal obligations.</p>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Security</h4>
                <p>We adopt reasonable security practices and procedures to protect your data. However, the transmission of information over the internet is not completely secure beyond our control.</p>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Withdrawal of Consent</h4>
                <p>You have an option to withdraw your consent by writing to our Grievance Officer. However, this may restrict your access to certain services.</p>
            </div>
        `
    },
    refunds: {
        title: "Refunds & Cancellation",
        content: `
            <div class="space-y-4">
                <h4 class="text-lg font-bold text-slate-800 mt-6">Cancellation Policy</h4>
                <ul class="list-disc pl-5 space-y-2">
                    <li>Cancellations will only be considered if request is made 1 day of placing the order.</li>
                    <li>Requests may not be entertained if the order has been communicated to sellers and they have initiated shipping.</li>
                    <li>Cancellation for perishable items like flowers/eatables is not accepted unless quality issues are established.</li>
                </ul>
                <h4 class="text-lg font-bold text-slate-800 mt-6">Refunds & Returns</h4>
                <p>We offer return/exchange within 1 day from the date of purchase. Item must be unused, in original packaging, and not from a sale category.</p>
                <p>Once approved after quality check, your refund will take approx 6 days to be processed.</p>
                <p>Damaged or defective items should be reported within 1 day of receipt.</p>
            </div>
        `
    },
    shipping: {
        title: "Shipping Policy",
        content: `
            <div class="space-y-4">
                <p>Orders are shipped through registered domestic courier companies and/or speed post only.</p>
                <ul class="list-disc pl-5 space-y-2">
                    <li>Orders are shipped within 5 days from the date of order/payment.</li>
                    <li>Platform Owner is not liable for any delay in delivery by the courier company or postal authority.</li>
                    <li>Delivery will be made to the address provided by the buyer.</li>
                    <li>Delivery of services will be confirmed via your registered email ID.</li>
                    <li>Shipping costs levied by the seller/platform are generally non-refundable.</li>
                </ul>
            </div>
        `
    }
};

function showLegal(type) {
    let modal = document.getElementById('legal-modal');
    
    if (!modal) {
        modal = document.createElement('div');
        modal.id = 'legal-modal';
        modal.className = 'fixed inset-0 z-[9999] flex items-center justify-center p-4 md:p-10 opacity-0 transition-opacity duration-300 pointer-events-none';
        modal.innerHTML = `
            <div class="absolute inset-0 bg-slate-900/60 backdrop-blur-md" onclick="closeLegal()"></div>
            <div class="relative bg-white w-full max-w-4xl h-full max-h-[85vh] rounded-[2rem] shadow-2xl overflow-hidden flex flex-col md:flex-row transform scale-95 transition-transform duration-300">
                <!-- Sidebar Nav -->
                <div class="w-full md:w-64 bg-slate-50 border-r border-slate-100 p-8 flex flex-col">
                    <div class="flex items-center gap-3 mb-10">
                        <img src="/favicon.png" class="h-8 w-8 rounded-lg shadow-sm" onerror="this.src='./favicon.png'">
                        <span class="font-bold text-slate-900 tracking-tight">Legal Center</span>
                    </div>
                    <nav class="space-y-2 flex-1">
                        <button onclick="switchLegal('terms')" id="btn-terms" class="w-full text-left px-4 py-3 rounded-xl text-sm font-semibold transition-all hover:bg-white">Terms of Use</button>
                        <button onclick="switchLegal('privacy')" id="btn-privacy" class="w-full text-left px-4 py-3 rounded-xl text-sm font-semibold transition-all hover:bg-white">Privacy Policy</button>
                        <button onclick="switchLegal('refunds')" id="btn-refunds" class="w-full text-left px-4 py-3 rounded-xl text-sm font-semibold transition-all hover:bg-white">Refund & Returns</button>
                        <button onclick="switchLegal('shipping')" id="btn-shipping" class="w-full text-left px-4 py-3 rounded-xl text-sm font-semibold transition-all hover:bg-white">Shipping Policy</button>
                    </nav>
                    <button onclick="closeLegal()" class="mt-8 w-full bg-slate-900 text-white py-3 rounded-xl text-sm font-bold shadow-lg hover:bg-slate-800 transition-all">Close</button>
                </div>
                <!-- Content Area -->
                <div class="flex-1 flex flex-col min-w-0 bg-white">
                    <div class="p-8 border-b border-slate-50 flex justify-between items-center">
                        <h2 id="legal-title" class="text-2xl font-black text-slate-900 uppercase">Terms & Conditions</h2>
                        <button onclick="closeLegal()" class="text-slate-400 hover:text-slate-900 transition-colors p-2">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                        </button>
                    </div>
                    <div id="legal-body" class="p-8 overflow-y-auto flex-1 text-slate-600 text-sm leading-relaxed scroll-smooth">
                        <!-- Content Injected Here -->
                    </div>
                </div>
            </div>
        `;
        document.body.appendChild(modal);
    }

    // Switch to content
    switchLegal(type || 'terms');

    // Show modal
    modal.classList.remove('opacity-0', 'pointer-events-none');
    modal.querySelector('.relative').classList.remove('scale-95');
    modal.querySelector('.relative').classList.add('scale-100');
    document.body.style.overflow = 'hidden';
}

function switchLegal(type) {
    const data = legalContent[type];
    if (!data) return;

    document.getElementById('legal-title').innerText = data.title;
    document.getElementById('legal-body').innerHTML = data.content;
    document.getElementById('legal-body').scrollTop = 0;

    // Update active button state
    ['terms', 'privacy', 'refunds', 'shipping'].forEach(t => {
        const btn = document.getElementById('btn-' + t);
        if (btn) {
            if (t === type) {
                btn.className = 'w-full text-left px-4 py-3 rounded-xl text-sm font-bold bg-white text-teal-600 shadow-sm ring-1 ring-slate-100';
            } else {
                btn.className = 'w-full text-left px-4 py-3 rounded-xl text-sm font-semibold text-slate-500 transition-all hover:bg-white hover:text-slate-900';
            }
        }
    });
}

function closeLegal() {
    const modal = document.getElementById('legal-modal');
    if (modal) {
        modal.classList.add('opacity-0', 'pointer-events-none');
        modal.querySelector('.relative').classList.remove('scale-100');
        modal.querySelector('.relative').classList.add('scale-95');
        document.body.style.overflow = '';
    }
}
